import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import organizationsRouter from "./organizations";
import agentsRouter from "./agents";
import tasksRouter from "./tasks";
import executionsRouter from "./executions";
import workflowsRouter from "./workflows";
import departmentsRouter from "./departments";
import skillsRouter from "./skills";
import analyticsRouter from "./analytics";
import toolsRouter from "./tools-api";
import salesRouter from "./sales";
import marketingRouter from "./marketing";
import subscriptionsRouter from "./subscriptions";
import providerKeysRouter from "./provider-keys";
import auditLogsRouter from "./audit-logs";
import notificationsRouter from "./notifications";
import onboardingRouter from "./onboarding";
import streamRouter from "./stream";
import metricsRouter from "./metrics";
import agentTemplatesRouter from "./agent-templates";
import workflowTemplatesRouter from "./workflow-templates";
import promptVersionsRouter from "./prompt-versions";
import costControlRouter from "./cost-control";
import { authenticate } from "../middleware/authenticate";
import publicLeadsRouter from "./public-leads";
import publicDemoRouter from "./public-demo";
import trialRouter from "./trial";
import referralRouter from "./referral";
import crmRouter from "./crm";
import kpiRouter from "./kpi";
import emailAutomationRouter from "./email-automation";
import marketplaceStoreRouter from "./marketplace-store";
import workforceCloudRouter from "./workforce-cloud";
import workforceGraphRouter from "./workforce-graph";
import workforceMonitoringRouter from "./workforce-monitoring";
import workforceFederationRouter from "./workforce-federation";
import workforceCollaborationRouter from "./workforce-collaboration";
import osKernelRouter from "./os-kernel";
import osResourcesRouter from "./os-resources";
import osPolicyRouter from "./os-policy";
import osGovernanceRouter from "./os-governance";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(publicLeadsRouter);
router.use(publicDemoRouter);

router.use(authenticate);

router.use(organizationsRouter);
router.use(agentsRouter);
router.use(tasksRouter);
router.use(executionsRouter);
router.use(workflowsRouter);
router.use(departmentsRouter);
router.use(skillsRouter);
router.use(analyticsRouter);
router.use(toolsRouter);
router.use(salesRouter);
router.use(marketingRouter);
router.use(subscriptionsRouter);
router.use(providerKeysRouter);
router.use(auditLogsRouter);
router.use(notificationsRouter);
router.use(onboardingRouter);
router.use(streamRouter);
router.use(metricsRouter);
router.use(agentTemplatesRouter);
router.use(workflowTemplatesRouter);
router.use(promptVersionsRouter);
router.use(costControlRouter);
router.use(trialRouter);
router.use(referralRouter);
router.use(crmRouter);
router.use(kpiRouter);
router.use(emailAutomationRouter);
router.use(marketplaceStoreRouter);
router.use(workforceCloudRouter);
router.use(workforceGraphRouter);
router.use(workforceMonitoringRouter);
router.use(workforceFederationRouter);
router.use(workforceCollaborationRouter);
router.use(osKernelRouter);
router.use(osResourcesRouter);
router.use(osPolicyRouter);
router.use(osGovernanceRouter);

export default router;
