import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import organizationsRouter from "./organizations";
import agentsRouter from "./agents";
import tasksRouter from "./tasks";
import executionsRouter from "./executions";
import workflowsRouter from "./workflows";
import departmentsRouter from "./departments";
import skillsRouter from "./skills";
import analyticsRouter from "./analytics";
import toolsRouter from "./tools-api";
import salesRouter from "./sales";
import marketingRouter from "./marketing";
import subscriptionsRouter from "./subscriptions";
import providerKeysRouter from "./provider-keys";
import auditLogsRouter from "./audit-logs";
import notificationsRouter from "./notifications";
import onboardingRouter from "./onboarding";
import streamRouter from "./stream";
import metricsRouter from "./metrics";
import agentTemplatesRouter from "./agent-templates";
import workflowTemplatesRouter from "./workflow-templates";
import promptVersionsRouter from "./prompt-versions";
import costControlRouter from "./cost-control";
import { authenticate } from "../middleware/authenticate";
import publicLeadsRouter from "./public-leads";
import publicDemoRouter from "./public-demo";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(publicLeadsRouter);
router.use(publicDemoRouter);

router.use(authenticate);

router.use(organizationsRouter);
router.use(agentsRouter);
router.use(tasksRouter);
router.use(executionsRouter);
router.use(workflowsRouter);
router.use(departmentsRouter);
router.use(skillsRouter);
router.use(analyticsRouter);
router.use(toolsRouter);
router.use(salesRouter);
router.use(marketingRouter);
router.use(subscriptionsRouter);
router.use(providerKeysRouter);
router.use(auditLogsRouter);
router.use(notificationsRouter);
router.use(onboardingRouter);
router.use(streamRouter);
router.use(metricsRouter);
router.use(agentTemplatesRouter);
router.use(workflowTemplatesRouter);
router.use(promptVersionsRouter);
router.use(costControlRouter);

export default router;
